# Generated by Django 3.0.2 on 2020-01-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cliente',
        ),
    ]
