# Generated by Django 3.0.2 on 2020-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20200205_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
