# Generated by Django 3.0.2 on 2020-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_perfil_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(default='Bogota, Colombia', max_length=30),
            preserve_default=False,
        ),
    ]
