# Generated by Django 3.0.2 on 2020-02-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_cliente'),
        ('cliente', '0003_cliente_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='perfil.Perfil'),
        ),
    ]
