# Generated by Django 3.0.2 on 2020-01-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_cliente'),
        ('cliente', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.Perfil'),
        ),
    ]
