# Generated by Django 3.0.2 on 2020-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(default='usuario', max_length=30),
            preserve_default=False,
        ),
    ]
